language: java

install: mvn clean install

script:
  - "echo 'adentro...'"
  - "echo $TRAVIS_PULL_REQUEST"
  - "
if [ ${TRAVIS_PULL_REQUEST} = 'false' ];
then
  echo $GAE_PASS | mvn appengine:update -Pupdate;
else
  echo $TRAVIS_PULL_REQUEST;
fi
"
jdk:
    - oraclejdk7
# whitelist
branches:
  only:
    - master
    - staging
