language: java

install: mvn clean install

script:
  - "echo 'adentro...'"
  - "echo $TRAVIS_PULL_REQUEST"
  - "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && { echo $GAE_PASS | mvn appengine:update -Pupdate } || { echo $TRAVIS_PULL_REQUEST; };"

jdk:
    - oraclejdk7

# whitelist
branches:
  only:
    - master
    - staging